services:
  muhportalweb:
    build: .
    container_name: muhportalweb
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: Europe/Rome
      VIRTUAL_HOST: portal.${DOMAIN}
    ports:
      - 3003:3003
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

networks:
  mac0:
    external: true
    name: mac0
